<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TCJ.Core" Version="$(TCJUpgradeVersion)" />
    <PackageReference Include="TCJ.DependencyInjection" Version="$(TCJUpgradeVersion)" />
    <PackageReference Include="TCJ.AspNetCore" Version="$(TCJUpgradeVersion)" />
  </ItemGroup>
</Project>
