using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace TCJ.Generators;

[Generator]
public sealed class StrongTypeGenerator : IIncrementalGenerator
{
    private const string StrongIdAttribute = "TCJ.Core.StrongTypes.StronglyTypedIdAttribute`1";
    private const string ValueObjectAttribute = "TCJ.Core.StrongTypes.ValueObjectAttribute`1";
    private const string GuidTypeName = "global::System.Guid";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var strongIdCandidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            StrongIdAttribute,
            static (node, _) => node is RecordDeclarationSyntax or StructDeclarationSyntax or ClassDeclarationSyntax,
            static (ctx, _) => CreateStrongIdModel(ctx));

        var guidStrongIds = strongIdCandidates
            .Where(static candidate => candidate is not null && candidate.IsGuidBacked && candidate.IsSupportedDeclaration)
            .Select(static (candidate, _) => candidate!);

        context.RegisterSourceOutput(guidStrongIds, static (spc, candidate) =>
        {
            spc.AddSource(candidate.HintName, GenerateGuidStrongId(candidate));
        });

        var valueObjectCandidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            ValueObjectAttribute,
            static (node, _) => node is RecordDeclarationSyntax or StructDeclarationSyntax or ClassDeclarationSyntax,
            static (ctx, _) => ctx.TargetSymbol.ToDisplayString())
            .Collect();

        context.RegisterSourceOutput(valueObjectCandidates, static (spc, candidates) =>
        {
            foreach (var symbol in candidates.OrderBy(static x => x, StringComparer.Ordinal))
            {
                _ = symbol;
            }
        });
    }

    private static StrongIdModel? CreateStrongIdModel(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol symbol || context.TargetNode is not RecordDeclarationSyntax declaration)
        {
            return null;
        }

        var attributeClass = context.Attributes.FirstOrDefault()?.AttributeClass;
        if (attributeClass is null || attributeClass.TypeArguments.Length != 1)
        {
            return null;
        }

        var backingType = attributeClass.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var isPartial = declaration.Modifiers.Any(static modifier => modifier.IsKind(SyntaxKind.PartialKeyword));
        var isReadOnly = declaration.Modifiers.Any(static modifier => modifier.IsKind(SyntaxKind.ReadOnlyKeyword));
        var isRecordStruct = declaration.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword);
        var isTopLevel = symbol.ContainingType is null;
        var isNonGeneric = symbol.TypeParameters.Length == 0;
        var isSupportedAccessibility = symbol.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal;
        var namespaceName = symbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : symbol.ContainingNamespace.ToDisplayString();
        var accessibility = symbol.DeclaredAccessibility == Accessibility.Public ? "public" : "internal";
        var typeName = EscapeIdentifier(symbol.Name);
        var qualifiedName = namespaceName is null ? symbol.Name : namespaceName + "." + symbol.Name;

        return new StrongIdModel(
            namespaceName,
            accessibility,
            typeName,
            $"TCJ.StronglyTypedId.{qualifiedName}.g.cs",
            string.Equals(backingType, GuidTypeName, StringComparison.Ordinal),
            isRecordStruct && isPartial && isReadOnly && isTopLevel && isNonGeneric && isSupportedAccessibility);
    }

    private static string GenerateGuidStrongId(StrongIdModel model)
    {
        var source = new StringBuilder();
        AppendLine(source, "// <auto-generated/>");
        AppendLine(source, "#nullable enable");
        AppendLine(source);

        if (model.NamespaceName is not null)
        {
            source.Append("namespace ").Append(model.NamespaceName);
            AppendLine(source);
            AppendLine(source, "{");
        }

        var indent = model.NamespaceName is null ? string.Empty : "    ";
        var memberIndent = indent + "    ";
        var bodyIndent = memberIndent + "    ";

        AppendLine(source, indent + "/// <summary>");
        AppendLine(source, indent + "/// Represents a strongly typed identifier backed by a GUID value.");
        AppendLine(source, indent + "/// </summary>");
        source.Append(indent)
            .Append(model.Accessibility)
            .Append(" readonly partial record struct ")
            .Append(model.TypeName);
        AppendLine(source);
        AppendLine(source, indent + "{");

        AppendLine(source, memberIndent + "/// <summary>");
        source.Append(memberIndent).Append("/// Initializes a new instance of the <see cref=\"")
            .Append(model.TypeName)
            .Append("\"/> struct.");
        AppendLine(source);
        AppendLine(source, memberIndent + "/// </summary>");
        AppendLine(source, memberIndent + "/// <param name=\"value\">The underlying identifier value.</param>");
        source.Append(memberIndent).Append("public ").Append(model.TypeName).Append("(global::System.Guid value)");
        AppendLine(source);
        AppendLine(source, memberIndent + "{");
        AppendLine(source, bodyIndent + "Value = value;");
        AppendLine(source, memberIndent + "}");
        AppendLine(source);

        AppendLine(source, memberIndent + "/// <summary>");
        AppendLine(source, memberIndent + "/// Gets the underlying identifier value.");
        AppendLine(source, memberIndent + "/// </summary>");
        AppendLine(source, memberIndent + "public global::System.Guid Value { get; }");
        AppendLine(source);

        AppendLine(source, memberIndent + "/// <summary>");
        AppendLine(source, memberIndent + "/// Gets a value indicating whether this identifier contains the default GUID value.");
        AppendLine(source, memberIndent + "/// </summary>");
        AppendLine(source, memberIndent + "public bool IsDefault => Value == global::System.Guid.Empty;");
        AppendLine(source);

        AppendLine(source, memberIndent + "/// <summary>");
        AppendLine(source, memberIndent + "/// Returns the identifier value in the canonical GUID D format.");
        AppendLine(source, memberIndent + "/// </summary>");
        AppendLine(source, memberIndent + "/// <returns>The canonical textual representation of the underlying GUID.</returns>");
        AppendLine(source, memberIndent + "public override string ToString() => Value.ToString(\"D\");");

        AppendLine(source, indent + "}");

        if (model.NamespaceName is not null)
        {
            AppendLine(source, "}");
        }

        return source.ToString();
    }

    private static void AppendLine(StringBuilder builder, string value = "")
    {
        builder.Append(value).Append('\n');
    }

    private static string EscapeIdentifier(string identifier)
    {
        return SyntaxFacts.GetKeywordKind(identifier) != SyntaxKind.None ||
               SyntaxFacts.GetContextualKeywordKind(identifier) != SyntaxKind.None
            ? "@" + identifier
            : identifier;
    }

    private sealed class StrongIdModel : IEquatable<StrongIdModel>
    {
        public StrongIdModel(
            string? namespaceName,
            string accessibility,
            string typeName,
            string hintName,
            bool isGuidBacked,
            bool isSupportedDeclaration)
        {
            NamespaceName = namespaceName;
            Accessibility = accessibility;
            TypeName = typeName;
            HintName = hintName;
            IsGuidBacked = isGuidBacked;
            IsSupportedDeclaration = isSupportedDeclaration;
        }

        public string? NamespaceName { get; }

        public string Accessibility { get; }

        public string TypeName { get; }

        public string HintName { get; }

        public bool IsGuidBacked { get; }

        public bool IsSupportedDeclaration { get; }

        public bool Equals(StrongIdModel? other)
        {
            return other is not null &&
                   string.Equals(NamespaceName, other.NamespaceName, StringComparison.Ordinal) &&
                   string.Equals(Accessibility, other.Accessibility, StringComparison.Ordinal) &&
                   string.Equals(TypeName, other.TypeName, StringComparison.Ordinal) &&
                   string.Equals(HintName, other.HintName, StringComparison.Ordinal) &&
                   IsGuidBacked == other.IsGuidBacked &&
                   IsSupportedDeclaration == other.IsSupportedDeclaration;
        }

        public override bool Equals(object? obj)
        {
            return obj is StrongIdModel other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                var hashCode = 17;
                hashCode = (hashCode * 31) + (NamespaceName is null ? 0 : StringComparer.Ordinal.GetHashCode(NamespaceName));
                hashCode = (hashCode * 31) + StringComparer.Ordinal.GetHashCode(Accessibility);
                hashCode = (hashCode * 31) + StringComparer.Ordinal.GetHashCode(TypeName);
                hashCode = (hashCode * 31) + StringComparer.Ordinal.GetHashCode(HintName);
                hashCode = (hashCode * 31) + IsGuidBacked.GetHashCode();
                hashCode = (hashCode * 31) + IsSupportedDeclaration.GetHashCode();
                return hashCode;
            }
        }
    }
}
