<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TCJ.Core" Version="$(TCJUpgradeVersion)" />
    <PackageReference Include="TCJ.Messaging" Version="$(TCJUpgradeVersion)" />
    <PackageReference Include="TCJ.Messaging.Kafka" Version="$(TCJUpgradeVersion)" />
  </ItemGroup>
</Project>
