<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\TestProject.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>TCJ.Messaging.ConformanceTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\TCJ.Core\TCJ.Core.csproj" />
    <ProjectReference Include="..\..\src\TCJ.Messaging\TCJ.Messaging.csproj" />
  </ItemGroup>
</Project>
