<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <IsAotCompatible>true</IsAotCompatible>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <EFOptimizeContext>true</EFOptimizeContext>
    <EFScaffoldModelStage>publish</EFScaffoldModelStage>
    <EFPrecompileQueriesStage>publish</EFPrecompileQueriesStage>
    <DbContextName>TcjEfNativeAot.ExperimentalNativeAotDbContext</DbContextName>
    <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.EntityFrameworkCore.GeneratedInterceptors</InterceptorsNamespaces>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TCJ.Core\TCJ.Core.csproj" />
    <ProjectReference Include="..\..\src\TCJ.EntityFrameworkCore\TCJ.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\TCJ.EntityFrameworkCore.SqlServer\TCJ.EntityFrameworkCore.SqlServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tasks">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
