using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using TCJ.Generators;

namespace TCJ.Generators.Tests;

public sealed class StrongTypeGeneratorTests
{
    [Fact]
    public void GuidStrongId_GeneratedSource_MatchesSnapshot()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using TCJ.Core.StrongTypes;

            namespace Sales.Orders;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;
            """);

        var result = RunGenerator(compilation);

        Assert.Empty(result.GeneratorDiagnostics);
        var generated = Assert.Single(result.GeneratedSources);
        Assert.Equal("TCJ.StronglyTypedId.Sales.Orders.OrderId.g.cs", generated.HintName);
        var expected =
            """
            // <auto-generated/>
            #nullable enable

            namespace Sales.Orders
            {
                /// <summary>
                /// Represents a strongly typed identifier backed by a GUID value.
                /// </summary>
                public readonly partial record struct OrderId
                {
                    /// <summary>
                    /// Initializes a new instance of the <see cref="OrderId"/> struct.
                    /// </summary>
                    /// <param name="value">The underlying identifier value.</param>
                    public OrderId(global::System.Guid value)
                    {
                        Value = value;
                    }

                    /// <summary>
                    /// Gets the underlying identifier value.
                    /// </summary>
                    public global::System.Guid Value { get; }

                    /// <summary>
                    /// Gets a value indicating whether this identifier contains the default GUID value.
                    /// </summary>
                    public bool IsDefault => Value == global::System.Guid.Empty;

                    /// <summary>
                    /// Returns the identifier value in the canonical GUID D format.
                    /// </summary>
                    /// <returns>The canonical textual representation of the underlying GUID.</returns>
                    public override string ToString() => Value.ToString("D");
                }
            }

            """;

        Assert.Equal(expected.ReplaceLineEndings("\n"), generated.Source);
        Assert.DoesNotContain("\r", generated.Source, StringComparison.Ordinal);
    }

    [Fact]
    public void GuidStrongId_CompilesAndExecutes_ValueDefaultEqualityHashingAndToString()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;
            """);

        var result = RunGenerator(compilation);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));

        var assembly = EmitAndLoad(result.OutputCompilation);
        var orderIdType = assembly.GetType("OrderId");
        Assert.NotNull(orderIdType);
        var valueProperty = orderIdType.GetProperty("Value");
        var isDefaultProperty = orderIdType.GetProperty("IsDefault");
        Assert.NotNull(valueProperty);
        Assert.NotNull(isDefaultProperty);
        Assert.False(valueProperty.CanWrite);
        var value = Guid.Parse("7a29be31-268d-4f2b-babc-fce0ce1cb46c");
        var differentValue = Guid.Parse("a7ef2a4f-4dde-42ee-b17c-0ea2f3c58996");

        var first = Activator.CreateInstance(orderIdType, value);
        var second = Activator.CreateInstance(orderIdType, value);
        var different = Activator.CreateInstance(orderIdType, differentValue);
        var defaultId = Activator.CreateInstance(orderIdType);
        Assert.NotNull(first);
        Assert.NotNull(second);
        Assert.NotNull(different);
        Assert.NotNull(defaultId);

        Assert.Equal(value, valueProperty.GetValue(first));
        Assert.False(Assert.IsType<bool>(isDefaultProperty.GetValue(first)));
        Assert.Equal(Guid.Empty, valueProperty.GetValue(defaultId));
        Assert.True(Assert.IsType<bool>(isDefaultProperty.GetValue(defaultId)));
        Assert.Equal(first, second);
        Assert.Equal(first.GetHashCode(), second.GetHashCode());
        Assert.NotEqual(first, different);
        Assert.Equal(value.ToString("D"), first.ToString());
    }

    [Fact]
    public void GuidStrongId_DoesNotExposeImplicitPrimitiveConversions()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;
            """);

        var result = RunGenerator(compilation);
        var orderId = Assert.IsAssignableFrom<ITypeSymbol>(result.OutputCompilation.GetTypeByMetadataName("OrderId"));
        var guid = Assert.IsAssignableFrom<ITypeSymbol>(result.OutputCompilation.GetTypeByMetadataName("System.Guid"));

        Assert.False(result.OutputCompilation.ClassifyConversion(orderId, guid).IsImplicit);
        Assert.False(result.OutputCompilation.ClassifyConversion(guid, orderId).IsImplicit);
        Assert.DoesNotContain(
            orderId.GetMembers().OfType<IMethodSymbol>(),
            static member => member.MethodKind == MethodKind.Conversion && member.Name == "op_Implicit");
    }

    [Fact]
    public void GuidStrongId_GeneratesMultipleTypesInOneCompilation()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using TCJ.Core.StrongTypes;

            namespace Sales;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;

            [StronglyTypedId<Guid>]
            public readonly partial record struct CustomerId;
            """);

        var result = RunGenerator(compilation);

        Assert.Equal(
            new[]
            {
                "TCJ.StronglyTypedId.Sales.CustomerId.g.cs",
                "TCJ.StronglyTypedId.Sales.OrderId.g.cs"
            },
            result.GeneratedSources.Select(static source => source.HintName).OrderBy(static hint => hint, StringComparer.Ordinal));
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
    }

    [Fact]
    public void GuidStrongId_SupportsNestedAndFileScopedNamespaces()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using TCJ.Core.StrongTypes;

            namespace Sales
            {
                namespace Orders
                {
                    [StronglyTypedId<Guid>]
                    public readonly partial record struct OrderId;
                }
            }
            """,
            """
            using TCJ.Core.StrongTypes;

            namespace Shipping.Labels;

            [StronglyTypedId<Guid>]
            internal readonly partial record struct LabelId;
            """);

        var result = RunGenerator(compilation);

        Assert.Equal(2, result.GeneratedSources.Count);
        Assert.Contains(result.GeneratedSources, static source => source.HintName == "TCJ.StronglyTypedId.Sales.Orders.OrderId.g.cs");
        Assert.Contains(result.GeneratedSources, static source => source.HintName == "TCJ.StronglyTypedId.Shipping.Labels.LabelId.g.cs");
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
    }

    [Fact]
    public void Generator_Output_IsStable_When_UnrelatedSyntaxChangesAreAdded()
    {
        var withoutUnrelatedSyntax = CreateCompilation(
            AttributeSource,
            """
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;
            """);

        var withUnrelatedSyntax = CreateCompilation(
            AttributeSource,
            """
            using TCJ.Core.StrongTypes;

            internal sealed class UnrelatedType
            {
            }

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;
            """);

        var first = RunGenerator(withoutUnrelatedSyntax);
        var second = RunGenerator(withUnrelatedSyntax);

        Assert.Equal(first.GeneratedSources, second.GeneratedSources);
    }

    [Fact]
    public void Generator_DoesNotGenerateIntegerStrongIdsBeforeIntegerSupportIssue()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<int>]
            public readonly partial record struct OrderId;
            """);

        var result = RunGenerator(compilation);

        Assert.Empty(result.GeneratorDiagnostics);
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void Generator_DoesNotGenerateGenericStrongIdsBeforeDiagnosticsIssue()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId<T>;
            """);

        var result = RunGenerator(compilation);

        Assert.Empty(result.GeneratorDiagnostics);
        Assert.Empty(result.GeneratedSources);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
    }

    [Fact]
    public void GuidStrongId_GeneratedCode_DoesNotUseReflection()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;
            """);

        var result = RunGenerator(compilation);
        var generated = Assert.Single(result.GeneratedSources);

        Assert.DoesNotContain("System.Reflection", generated.Source, StringComparison.Ordinal);
        Assert.DoesNotContain("GetType(", generated.Source, StringComparison.Ordinal);
        Assert.DoesNotContain("Activator", generated.Source, StringComparison.Ordinal);
    }

    private static GeneratorResult RunGenerator(CSharpCompilation compilation)
    {
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new StrongTypeGenerator());

        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation,
            out var outputCompilation,
            out var diagnostics);

        var runResult = driver.GetRunResult();
        var generatedSources = runResult.Results
            .Where(static result => !result.GeneratedSources.IsDefault)
            .SelectMany(static result => result.GeneratedSources)
            .Select(static source => new GeneratedSource(source.HintName, source.SourceText.ToString()))
            .OrderBy(static source => source.HintName, StringComparer.Ordinal)
            .ToArray();

        return new GeneratorResult(
            diagnostics,
            generatedSources,
            (CSharpCompilation)outputCompilation);
    }

    private static CSharpCompilation CreateCompilation(params string[] sources)
    {
        var parseOptions = new CSharpParseOptions(LanguageVersion.Latest);
        var syntaxTrees = sources
            .Select(source => CSharpSyntaxTree.ParseText(source, parseOptions))
            .ToArray();

        return CSharpCompilation.Create(
            "Test_" + Guid.NewGuid().ToString("N"),
            syntaxTrees,
            TrustedPlatformReferences,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    private static Assembly EmitAndLoad(CSharpCompilation compilation)
    {
        using var stream = new MemoryStream();
        var emitResult = compilation.Emit(stream);
        Assert.True(
            emitResult.Success,
            string.Join(Environment.NewLine, emitResult.Diagnostics.Select(static diagnostic => diagnostic.ToString())));

        return Assembly.Load(stream.ToArray());
    }

    private static readonly MetadataReference[] TrustedPlatformReferences =
        ((string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES"))!
        .Split(Path.PathSeparator)
        .Select(static path => MetadataReference.CreateFromFile(path))
        .ToArray();

    private sealed record GeneratedSource(string HintName, string Source);

    private sealed record GeneratorResult(
        IReadOnlyList<Diagnostic> GeneratorDiagnostics,
        IReadOnlyList<GeneratedSource> GeneratedSources,
        CSharpCompilation OutputCompilation);

    private const string AttributeSource =
        """
        namespace TCJ.Core.StrongTypes;

        [System.AttributeUsage(System.AttributeTargets.Struct)]
        public sealed class StronglyTypedIdAttribute<T> : System.Attribute
        {
        }

        [System.AttributeUsage(System.AttributeTargets.Struct | System.AttributeTargets.Class)]
        public sealed class ValueObjectAttribute<T> : System.Attribute
        {
        }
        """;
}
