using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using TCJ.Generators;

namespace TCJ.Generators.Tests;

public sealed class StrongTypeGeneratorTests
{
    [Fact]
    public void GuidStrongId_GeneratedSource_MatchesSnapshot()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            namespace Sales.Orders;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;
            """);

        var result = RunGenerator(compilation);

        Assert.Empty(result.GeneratorDiagnostics);
        var generated = Assert.Single(result.GeneratedSources);
        Assert.Equal("TCJ.StronglyTypedId.Sales.Orders.OrderId.g.cs", generated.HintName);
        var expected =
            """
            // <auto-generated/>
            #nullable enable

            namespace Sales.Orders
            {
                /// <summary>
                /// Represents a strongly typed identifier backed by a GUID value.
                /// </summary>
                [global::System.Text.Json.Serialization.JsonConverter(typeof(OrderId.StrongIdJsonConverter))]
                public readonly partial record struct OrderId : global::System.IParsable<OrderId>, global::System.ISpanParsable<OrderId>, global::System.IFormattable, global::System.ISpanFormattable
                {
                    /// <summary>
                    /// Initializes a new instance of the <see cref="OrderId"/> struct.
                    /// </summary>
                    /// <param name="value">The underlying identifier value.</param>
                    public OrderId(global::System.Guid value)
                    {
                        Value = value;
                    }

                    /// <summary>
                    /// Gets the underlying identifier value.
                    /// </summary>
                    public global::System.Guid Value { get; }

                    /// <summary>
                    /// Gets a value indicating whether this identifier contains the default GUID value.
                    /// </summary>
                    public bool IsDefault => Value == global::System.Guid.Empty;

                    /// <summary>
                    /// Creates a new strongly typed identifier from a version 4 GUID produced by the supplied generator.
                    /// </summary>
                    /// <param name="generator">The GUID generator used to create the underlying value.</param>
                    /// <returns>A strongly typed identifier containing the exact generated GUID.</returns>
                    public static OrderId New(global::TCJ.Core.Identifiers.IGuidGenerator generator)
                    {
                        global::System.ArgumentNullException.ThrowIfNull(generator);
                        return new OrderId(generator.Create());
                    }

                    /// <summary>
                    /// Creates a new strongly typed identifier from a version 7 GUID produced by the supplied generator.
                    /// </summary>
                    /// <param name="generator">The GUID generator used to create the underlying value.</param>
                    /// <returns>A strongly typed identifier containing the exact generated GUID.</returns>
                    public static OrderId NewVersion7(global::TCJ.Core.Identifiers.IGuidGenerator generator)
                    {
                        global::System.ArgumentNullException.ThrowIfNull(generator);
                        return new OrderId(generator.CreateVersion7());
                    }

                    /// <summary>
                    /// Parses a canonical GUID D-format string into a strongly typed identifier.
                    /// </summary>
                    /// <param name="s">The canonical GUID D-format text to parse.</param>
                    /// <returns>The parsed strongly typed identifier.</returns>
                    public static OrderId Parse(string s) => new(global::System.Guid.ParseExact(s, "D"));

                    /// <summary>
                    /// Parses a canonical GUID D-format string into a strongly typed identifier.
                    /// </summary>
                    /// <param name="s">The canonical GUID D-format text to parse.</param>
                    /// <param name="provider">Ignored. Parsing always uses culture-stable GUID semantics.</param>
                    /// <returns>The parsed strongly typed identifier.</returns>
                    public static OrderId Parse(string s, global::System.IFormatProvider? provider) => new(global::System.Guid.ParseExact(s, "D"));

                    /// <summary>
                    /// Parses canonical GUID D-format characters into a strongly typed identifier.
                    /// </summary>
                    /// <param name="s">The canonical GUID D-format characters to parse.</param>
                    /// <returns>The parsed strongly typed identifier.</returns>
                    public static OrderId Parse(global::System.ReadOnlySpan<char> s) => new(global::System.Guid.ParseExact(s, "D"));

                    /// <summary>
                    /// Parses canonical GUID D-format characters into a strongly typed identifier.
                    /// </summary>
                    /// <param name="s">The canonical GUID D-format characters to parse.</param>
                    /// <param name="provider">Ignored. Parsing always uses culture-stable GUID semantics.</param>
                    /// <returns>The parsed strongly typed identifier.</returns>
                    public static OrderId Parse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider) => new(global::System.Guid.ParseExact(s, "D"));

                    /// <summary>
                    /// Tries to parse canonical GUID D-format text into a strongly typed identifier.
                    /// </summary>
                    /// <param name="s">The canonical GUID D-format text to parse.</param>
                    /// <param name="result">When successful, receives the parsed identifier; otherwise, the default identifier.</param>
                    /// <returns><see langword="true"/> when parsing succeeds; otherwise, <see langword="false"/>.</returns>
                    public static bool TryParse(string? s, out OrderId result) => TryParse(s, null, out result);

                    /// <summary>
                    /// Tries to parse canonical GUID D-format text into a strongly typed identifier.
                    /// </summary>
                    /// <param name="s">The canonical GUID D-format text to parse.</param>
                    /// <param name="provider">Ignored. Parsing always uses culture-stable GUID semantics.</param>
                    /// <param name="result">When successful, receives the parsed identifier; otherwise, the default identifier.</param>
                    /// <returns><see langword="true"/> when parsing succeeds; otherwise, <see langword="false"/>.</returns>
                    public static bool TryParse(string? s, global::System.IFormatProvider? provider, out OrderId result)
                    {
                        if (global::System.Guid.TryParseExact(s, "D", out var value))
                        {
                            result = new OrderId(value);
                            return true;
                        }

                        result = default;
                        return false;
                    }

                    /// <summary>
                    /// Tries to parse canonical GUID D-format characters into a strongly typed identifier.
                    /// </summary>
                    /// <param name="s">The canonical GUID D-format characters to parse.</param>
                    /// <param name="result">When successful, receives the parsed identifier; otherwise, the default identifier.</param>
                    /// <returns><see langword="true"/> when parsing succeeds; otherwise, <see langword="false"/>.</returns>
                    public static bool TryParse(global::System.ReadOnlySpan<char> s, out OrderId result) => TryParse(s, null, out result);

                    /// <summary>
                    /// Tries to parse canonical GUID D-format characters into a strongly typed identifier.
                    /// </summary>
                    /// <param name="s">The canonical GUID D-format characters to parse.</param>
                    /// <param name="provider">Ignored. Parsing always uses culture-stable GUID semantics.</param>
                    /// <param name="result">When successful, receives the parsed identifier; otherwise, the default identifier.</param>
                    /// <returns><see langword="true"/> when parsing succeeds; otherwise, <see langword="false"/>.</returns>
                    public static bool TryParse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, out OrderId result)
                    {
                        if (global::System.Guid.TryParseExact(s, "D", out var value))
                        {
                            result = new OrderId(value);
                            return true;
                        }

                        result = default;
                        return false;
                    }

                    /// <summary>
                    /// Returns the identifier value in the canonical GUID D format.
                    /// </summary>
                    /// <returns>The canonical textual representation of the underlying GUID.</returns>
                    public override string ToString() => Value.ToString("D", global::System.Globalization.CultureInfo.InvariantCulture);

                    /// <summary>
                    /// Formats the identifier using a GUID format specifier and culture-stable semantics.
                    /// </summary>
                    /// <param name="format">A GUID format specifier. Null or empty uses the canonical D format.</param>
                    /// <param name="formatProvider">Ignored. Formatting always uses invariant culture.</param>
                    /// <returns>The formatted identifier.</returns>
                    public string ToString(string? format, global::System.IFormatProvider? formatProvider) =>
                        Value.ToString(global::System.String.IsNullOrEmpty(format) ? "D" : format, global::System.Globalization.CultureInfo.InvariantCulture);

                    /// <summary>
                    /// Tries to format the identifier into the supplied character span without allocating a string.
                    /// </summary>
                    /// <param name="destination">The span that receives the formatted identifier.</param>
                    /// <param name="charsWritten">When successful, receives the number of characters written.</param>
                    /// <param name="format">A GUID format specifier. Empty uses the canonical D format.</param>
                    /// <param name="provider">Ignored. Formatting always uses culture-stable GUID semantics.</param>
                    /// <returns><see langword="true"/> if the destination was large enough; otherwise, <see langword="false"/>.</returns>
                    public bool TryFormat(global::System.Span<char> destination, out int charsWritten, global::System.ReadOnlySpan<char> format = default, global::System.IFormatProvider? provider = null)
                    {
                        if (format.IsEmpty)
                        {
                            format = "D";
                        }

                        return Value.TryFormat(destination, out charsWritten, format);
                    }

                    /// <summary>
                    /// Explicitly converts a GUID value to the strongly typed identifier.
                    /// </summary>
                    /// <param name="value">The underlying GUID value.</param>
                    /// <returns>A strongly typed identifier containing the exact GUID value.</returns>
                    public static explicit operator OrderId(global::System.Guid value) => new(value);

                    /// <summary>
                    /// Explicitly converts the strongly typed identifier to its underlying GUID value.
                    /// </summary>
                    /// <param name="value">The strongly typed identifier.</param>
                    /// <returns>The exact underlying GUID value.</returns>
                    public static explicit operator global::System.Guid(OrderId value) => value.Value;

                    /// <summary>
                    /// Provides provider-neutral conversion expressions between this strongly typed identifier and its backing value.
                    /// </summary>
                    public static class StrongIdConversion
                    {
                        /// <summary>
                        /// Gets the conversion expression from the strongly typed identifier to its backing value.
                        /// </summary>
                        public static global::System.Linq.Expressions.Expression<global::System.Func<OrderId, global::System.Guid>> ToBackingValue { get; } = static value => value.Value;

                        /// <summary>
                        /// Gets the conversion expression from the backing value to the strongly typed identifier.
                        /// </summary>
                        public static global::System.Linq.Expressions.Expression<global::System.Func<global::System.Guid, OrderId>> FromBackingValue { get; } = static value => new OrderId(value);
                    }

                    /// <summary>
                    /// Converts this strongly typed identifier to and from its scalar System.Text.Json representation.
                    /// </summary>
                    public sealed class StrongIdJsonConverter : global::System.Text.Json.Serialization.JsonConverter<OrderId>
                    {
                        /// <summary>
                        /// Initializes a new instance of the generated Strong ID JSON converter.
                        /// </summary>
                        public StrongIdJsonConverter()
                        {
                        }

                        /// <inheritdoc />
                        public override bool HandleNull => true;

                        /// <inheritdoc />
                        public override OrderId Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
                        {
                            if (reader.TokenType != global::System.Text.Json.JsonTokenType.String)
                            {
                                throw new global::System.Text.Json.JsonException("Expected a JSON string token for OrderId.");
                            }

                            if (!reader.TryGetGuid(out var value))
                            {
                                throw new global::System.Text.Json.JsonException("Invalid GUID value for OrderId.");
                            }

                            return new OrderId(value);
                        }

                        /// <inheritdoc />
                        public override void Write(global::System.Text.Json.Utf8JsonWriter writer, OrderId value, global::System.Text.Json.JsonSerializerOptions options)
                        {
                            writer.WriteStringValue(value.Value);
                        }
                    }
                }
            }

            """;

        Assert.Equal(expected.ReplaceLineEndings("\n"), generated.Source);
        Assert.DoesNotContain("\r", generated.Source, StringComparison.Ordinal);
    }

    [Fact]
    public void GuidStrongId_CompilesAndExecutes_ValueDefaultEqualityHashingAndToString()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;
            """);

        var result = RunGenerator(compilation);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));

        var assembly = EmitAndLoad(result.OutputCompilation);
        var orderIdType = assembly.GetType("OrderId");
        Assert.NotNull(orderIdType);
        var valueProperty = orderIdType.GetProperty("Value");
        var isDefaultProperty = orderIdType.GetProperty("IsDefault");
        Assert.NotNull(valueProperty);
        Assert.NotNull(isDefaultProperty);
        Assert.False(valueProperty.CanWrite);
        var value = Guid.Parse("7a29be31-268d-4f2b-babc-fce0ce1cb46c");
        var differentValue = Guid.Parse("a7ef2a4f-4dde-42ee-b17c-0ea2f3c58996");

        var first = Activator.CreateInstance(orderIdType, value);
        var second = Activator.CreateInstance(orderIdType, value);
        var different = Activator.CreateInstance(orderIdType, differentValue);
        var defaultId = Activator.CreateInstance(orderIdType);
        Assert.NotNull(first);
        Assert.NotNull(second);
        Assert.NotNull(different);
        Assert.NotNull(defaultId);

        Assert.Equal(value, valueProperty.GetValue(first));
        Assert.False(Assert.IsType<bool>(isDefaultProperty.GetValue(first)));
        Assert.Equal(Guid.Empty, valueProperty.GetValue(defaultId));
        Assert.True(Assert.IsType<bool>(isDefaultProperty.GetValue(defaultId)));
        Assert.Equal(first, second);
        Assert.Equal(first.GetHashCode(), second.GetHashCode());
        Assert.NotEqual(first, different);
        Assert.Equal(value.ToString("D"), first.ToString());
    }

    [Fact]
    public void GuidStrongId_ImplementsParsingAndFormattingContracts()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;
            """);

        var result = RunGenerator(compilation);

        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
        var orderId = Assert.IsAssignableFrom<INamedTypeSymbol>(result.OutputCompilation.GetTypeByMetadataName("OrderId"));
        var interfaces = orderId.AllInterfaces.Select(static type => type.ToDisplayString()).ToArray();

        Assert.Contains("System.IParsable<OrderId>", interfaces);
        Assert.Contains("System.ISpanParsable<OrderId>", interfaces);
        Assert.Contains("System.IFormattable", interfaces);
        Assert.Contains("System.ISpanFormattable", interfaces);
    }

    [Fact]
    public void GuidStrongId_ParsesFormatsAndExplicitlyConverts_WithStableInvariantWireSemantics()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using System.Globalization;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;

            public static class StrongIdProbe
            {
                public static bool Verify()
                {
                    var previousCulture = CultureInfo.CurrentCulture;
                    var previousUiCulture = CultureInfo.CurrentUICulture;

                    try
                    {
                        CultureInfo.CurrentCulture = new CultureInfo("fa-IR");
                        CultureInfo.CurrentUICulture = new CultureInfo("fa-IR");

                        var value = Guid.Parse("7a29be31-268d-4f2b-babc-fce0ce1cb46c");
                        var expectedText = value.ToString("D", CultureInfo.InvariantCulture);
                        var id = (OrderId)value;

                        if ((Guid)id != value || id.Value != value)
                        {
                            return false;
                        }

                        if (!string.Equals(id.ToString(), expectedText, StringComparison.Ordinal))
                        {
                            return false;
                        }

                        if (!string.Equals(id.ToString(null, CultureInfo.CurrentCulture), expectedText, StringComparison.Ordinal))
                        {
                            return false;
                        }

                        var parsed = OrderId.Parse(expectedText);
                        var parsedWithProvider = OrderId.Parse(expectedText, CultureInfo.CurrentCulture);
                        var parsedFromSpan = OrderId.Parse(expectedText.AsSpan(), CultureInfo.CurrentCulture);
                        if (parsed != id || parsedWithProvider != id || parsedFromSpan != id)
                        {
                            return false;
                        }

                        if (!OrderId.TryParse(expectedText, out var tryParsed) || tryParsed != id)
                        {
                            return false;
                        }

                        if (!OrderId.TryParse(expectedText.AsSpan(), CultureInfo.CurrentCulture, out var spanParsed) || spanParsed != id)
                        {
                            return false;
                        }

                        if (OrderId.TryParse("not-a-guid", out var invalid) || !invalid.IsDefault)
                        {
                            return false;
                        }

                        if (OrderId.TryParse(null, out var nullInput) || !nullInput.IsDefault)
                        {
                            return false;
                        }

                        if (OrderId.TryParse(value.ToString("N"), out _))
                        {
                            return false;
                        }

                        try
                        {
                            _ = OrderId.Parse("not-a-guid");
                            return false;
                        }
                        catch (FormatException)
                        {
                        }

                        Span<char> buffer = stackalloc char[36];
                        if (!id.TryFormat(buffer, out var charsWritten) || charsWritten != 36)
                        {
                            return false;
                        }

                        if (!string.Equals(new string(buffer[..charsWritten]), expectedText, StringComparison.Ordinal))
                        {
                            return false;
                        }

                        Span<char> tooSmall = stackalloc char[35];
                        if (id.TryFormat(tooSmall, out _))
                        {
                            return false;
                        }

                        return true;
                    }
                    finally
                    {
                        CultureInfo.CurrentCulture = previousCulture;
                        CultureInfo.CurrentUICulture = previousUiCulture;
                    }
                }
            }
            """);

        var result = RunGenerator(compilation);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));

        var assembly = EmitAndLoad(result.OutputCompilation);
        var probeType = Assert.IsAssignableFrom<Type>(assembly.GetType("StrongIdProbe"));
        var verify = Assert.IsAssignableFrom<MethodInfo>(probeType.GetMethod("Verify", BindingFlags.Public | BindingFlags.Static));

        Assert.True(Assert.IsType<bool>(verify.Invoke(null, null)));
    }

    [Fact]
    public void GuidStrongId_CreationHelpersUseInjectedGeneratorPreserveExactValuesAndGuardNull()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.Identifiers;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;

            public sealed class FakeGuidGenerator : IGuidGenerator
            {
                private readonly Guid _version4;
                private readonly Guid _version7;

                public FakeGuidGenerator(Guid version4, Guid version7)
                {
                    _version4 = version4;
                    _version7 = version7;
                }

                public int CreateCalls { get; private set; }

                public int CreateVersion7Calls { get; private set; }

                public Guid Create()
                {
                    CreateCalls++;
                    return _version4;
                }

                public Guid CreateVersion7()
                {
                    CreateVersion7Calls++;
                    return _version7;
                }
            }

            public static class GuidCreationProbe
            {
                public static bool Verify()
                {
                    var version4 = Guid.Parse("11111111-1111-4111-8111-111111111111");
                    var version7 = Guid.Parse("22222222-2222-7222-8222-222222222222");
                    var generator = new FakeGuidGenerator(version4, version7);

                    var randomId = OrderId.New(generator);
                    var orderedId = OrderId.NewVersion7(generator);

                    if (randomId.Value != version4 || orderedId.Value != version7)
                    {
                        return false;
                    }

                    if (generator.CreateCalls != 1 || generator.CreateVersion7Calls != 1)
                    {
                        return false;
                    }

                    try
                    {
                        _ = OrderId.New(null!);
                        return false;
                    }
                    catch (ArgumentNullException exception) when (exception.ParamName == "generator")
                    {
                    }

                    try
                    {
                        _ = OrderId.NewVersion7(null!);
                        return false;
                    }
                    catch (ArgumentNullException exception) when (exception.ParamName == "generator")
                    {
                    }

                    return true;
                }
            }
            """);

        var result = RunGenerator(compilation);
        Assert.Empty(result.GeneratorDiagnostics);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));

        var generated = Assert.Single(result.GeneratedSources);
        Assert.Contains("generator.Create()", generated.Source, StringComparison.Ordinal);
        Assert.Contains("generator.CreateVersion7()", generated.Source, StringComparison.Ordinal);
        Assert.DoesNotContain("Guid.NewGuid", generated.Source, StringComparison.Ordinal);
        Assert.DoesNotContain("new global::TCJ.Core.Identifiers.GuidGenerator", generated.Source, StringComparison.Ordinal);
        Assert.DoesNotContain("ServiceProvider", generated.Source, StringComparison.Ordinal);

        var assembly = EmitAndLoad(result.OutputCompilation);
        var probeType = Assert.IsAssignableFrom<Type>(assembly.GetType("GuidCreationProbe"));
        var verify = Assert.IsAssignableFrom<MethodInfo>(probeType.GetMethod("Verify", BindingFlags.Public | BindingFlags.Static));

        Assert.True(Assert.IsType<bool>(verify.Invoke(null, null)));
    }

    [Fact]
    public void NumericStrongIds_DoNotGenerateGuidCreationHelpers()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<int>]
            public readonly partial record struct IntId;

            [StronglyTypedId<long>]
            public readonly partial record struct LongId;
            """);

        var result = RunGenerator(compilation);

        Assert.Empty(result.GeneratorDiagnostics);
        Assert.Equal(2, result.GeneratedSources.Count);
        Assert.All(result.GeneratedSources, static generated =>
        {
            Assert.DoesNotContain("IGuidGenerator", generated.Source, StringComparison.Ordinal);
            Assert.DoesNotContain(" New(", generated.Source, StringComparison.Ordinal);
            Assert.DoesNotContain("NewVersion7", generated.Source, StringComparison.Ordinal);
        });
    }

    [Fact]
    public void GuidStrongId_DoesNotExposeImplicitPrimitiveConversions()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;
            """);

        var result = RunGenerator(compilation);
        var orderId = Assert.IsAssignableFrom<ITypeSymbol>(result.OutputCompilation.GetTypeByMetadataName("OrderId"));
        var guid = Assert.IsAssignableFrom<ITypeSymbol>(result.OutputCompilation.GetTypeByMetadataName("System.Guid"));

        var toGuid = result.OutputCompilation.ClassifyConversion(orderId, guid);
        var fromGuid = result.OutputCompilation.ClassifyConversion(guid, orderId);

        Assert.False(toGuid.IsImplicit);
        Assert.False(fromGuid.IsImplicit);
        Assert.True(toGuid.IsExplicit);
        Assert.True(fromGuid.IsExplicit);
        Assert.DoesNotContain(
            orderId.GetMembers().OfType<IMethodSymbol>(),
            static member => member.MethodKind == MethodKind.Conversion && member.Name == "op_Implicit");
        Assert.Equal(
            2,
            orderId.GetMembers().OfType<IMethodSymbol>().Count(
                static member => member.MethodKind == MethodKind.Conversion && member.Name == "op_Explicit"));
    }

    [Fact]
    public void GuidStrongId_GeneratesMultipleTypesInOneCompilation()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            namespace Sales;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;

            [StronglyTypedId<Guid>]
            public readonly partial record struct CustomerId;
            """);

        var result = RunGenerator(compilation);

        Assert.Equal(
            new[]
            {
                "TCJ.StronglyTypedId.Sales.CustomerId.g.cs",
                "TCJ.StronglyTypedId.Sales.OrderId.g.cs"
            },
            result.GeneratedSources.Select(static source => source.HintName).OrderBy(static hint => hint, StringComparer.Ordinal));
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
    }

    [Fact]
    public void GuidStrongId_SupportsNestedAndFileScopedNamespaces()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            namespace Sales
            {
                namespace Orders
                {
                    [StronglyTypedId<Guid>]
                    public readonly partial record struct OrderId;
                }
            }
            """,
            """
            using System;
            using TCJ.Core.StrongTypes;

            namespace Shipping.Labels;

            [StronglyTypedId<Guid>]
            internal readonly partial record struct LabelId;
            """);

        var result = RunGenerator(compilation);

        Assert.Equal(2, result.GeneratedSources.Count);
        Assert.Contains(result.GeneratedSources, static source => source.HintName == "TCJ.StronglyTypedId.Sales.Orders.OrderId.g.cs");
        Assert.Contains(result.GeneratedSources, static source => source.HintName == "TCJ.StronglyTypedId.Shipping.Labels.LabelId.g.cs");
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
    }

    [Fact]
    public void Generator_Output_IsStable_When_UnrelatedSyntaxChangesAreAdded()
    {
        var withoutUnrelatedSyntax = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;
            """);

        var withUnrelatedSyntax = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            internal sealed class UnrelatedType
            {
            }

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;
            """);

        var first = RunGenerator(withoutUnrelatedSyntax);
        var second = RunGenerator(withUnrelatedSyntax);

        Assert.Equal(first.GeneratedSources, second.GeneratedSources);
    }

    [Theory]
    [InlineData("int", "IntId", "global::System.Int32", "32-bit integer")]
    [InlineData("long", "LongId", "global::System.Int64", "64-bit integer")]
    public void NumericStrongId_GeneratedSource_MatchesSnapshot(
        string backingKeyword,
        string typeName,
        string backingType,
        string backingDescription)
    {
        var compilation = CreateCompilation(
            AttributeSource,
            $$"""
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<{{backingKeyword}}>]
            public readonly partial record struct {{typeName}};
            """);

        var result = RunGenerator(compilation);

        Assert.Empty(result.GeneratorDiagnostics);
        var generated = Assert.Single(result.GeneratedSources);
        Assert.Equal($"TCJ.StronglyTypedId.{typeName}.g.cs", generated.HintName);

        var expected =
            $$"""
            // <auto-generated/>
            #nullable enable

            /// <summary>
            /// Represents a strongly typed identifier backed by a {{backingDescription}} value.
            /// </summary>
            [global::System.Text.Json.Serialization.JsonConverter(typeof({{typeName}}.StrongIdJsonConverter))]
            public readonly partial record struct {{typeName}} : global::System.IParsable<{{typeName}}>, global::System.ISpanParsable<{{typeName}}>, global::System.IFormattable, global::System.ISpanFormattable
            {
                /// <summary>
                /// Initializes a new instance of the <see cref="{{typeName}}"/> struct.
                /// </summary>
                /// <param name="value">The underlying identifier value.</param>
                public {{typeName}}({{backingType}} value)
                {
                    Value = value;
                }

                /// <summary>
                /// Gets the underlying identifier value.
                /// </summary>
                public {{backingType}} Value { get; }

                /// <summary>
                /// Gets a value indicating whether this identifier contains the default numeric value.
                /// </summary>
                public bool IsDefault => Value == default;

                /// <summary>
                /// Parses invariant base-10 integer text into a strongly typed identifier.
                /// </summary>
                /// <param name="s">The invariant integer text to parse.</param>
                /// <returns>The parsed strongly typed identifier.</returns>
                public static {{typeName}} Parse(string s) => new({{backingType}}.Parse(s, global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture));

                /// <summary>
                /// Parses invariant base-10 integer text into a strongly typed identifier.
                /// </summary>
                /// <param name="s">The invariant integer text to parse.</param>
                /// <param name="provider">Ignored. Parsing always uses invariant culture.</param>
                /// <returns>The parsed strongly typed identifier.</returns>
                public static {{typeName}} Parse(string s, global::System.IFormatProvider? provider) => Parse(s);

                /// <summary>
                /// Parses invariant base-10 integer characters into a strongly typed identifier.
                /// </summary>
                /// <param name="s">The invariant integer characters to parse.</param>
                /// <returns>The parsed strongly typed identifier.</returns>
                public static {{typeName}} Parse(global::System.ReadOnlySpan<char> s) => new({{backingType}}.Parse(s, global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture));

                /// <summary>
                /// Parses invariant base-10 integer characters into a strongly typed identifier.
                /// </summary>
                /// <param name="s">The invariant integer characters to parse.</param>
                /// <param name="provider">Ignored. Parsing always uses invariant culture.</param>
                /// <returns>The parsed strongly typed identifier.</returns>
                public static {{typeName}} Parse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider) => Parse(s);

                /// <summary>
                /// Tries to parse invariant base-10 integer text into a strongly typed identifier.
                /// </summary>
                /// <param name="s">The invariant integer text to parse.</param>
                /// <param name="result">When successful, receives the parsed identifier; otherwise, the default identifier.</param>
                /// <returns><see langword="true"/> when parsing succeeds; otherwise, <see langword="false"/>.</returns>
                public static bool TryParse(string? s, out {{typeName}} result) => TryParse(s, null, out result);

                /// <summary>
                /// Tries to parse invariant base-10 integer text into a strongly typed identifier.
                /// </summary>
                /// <param name="s">The invariant integer text to parse.</param>
                /// <param name="provider">Ignored. Parsing always uses invariant culture.</param>
                /// <param name="result">When successful, receives the parsed identifier; otherwise, the default identifier.</param>
                /// <returns><see langword="true"/> when parsing succeeds; otherwise, <see langword="false"/>.</returns>
                public static bool TryParse(string? s, global::System.IFormatProvider? provider, out {{typeName}} result)
                {
                    if ({{backingType}}.TryParse(s, global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out var value))
                    {
                        result = new {{typeName}}(value);
                        return true;
                    }

                    result = default;
                    return false;
                }

                /// <summary>
                /// Tries to parse invariant base-10 integer characters into a strongly typed identifier.
                /// </summary>
                /// <param name="s">The invariant integer characters to parse.</param>
                /// <param name="result">When successful, receives the parsed identifier; otherwise, the default identifier.</param>
                /// <returns><see langword="true"/> when parsing succeeds; otherwise, <see langword="false"/>.</returns>
                public static bool TryParse(global::System.ReadOnlySpan<char> s, out {{typeName}} result) => TryParse(s, null, out result);

                /// <summary>
                /// Tries to parse invariant base-10 integer characters into a strongly typed identifier.
                /// </summary>
                /// <param name="s">The invariant integer characters to parse.</param>
                /// <param name="provider">Ignored. Parsing always uses invariant culture.</param>
                /// <param name="result">When successful, receives the parsed identifier; otherwise, the default identifier.</param>
                /// <returns><see langword="true"/> when parsing succeeds; otherwise, <see langword="false"/>.</returns>
                public static bool TryParse(global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, out {{typeName}} result)
                {
                    if ({{backingType}}.TryParse(s, global::System.Globalization.NumberStyles.Integer, global::System.Globalization.CultureInfo.InvariantCulture, out var value))
                    {
                        result = new {{typeName}}(value);
                        return true;
                    }

                    result = default;
                    return false;
                }

                /// <summary>
                /// Returns the identifier using invariant base-10 integer formatting.
                /// </summary>
                /// <returns>The invariant textual representation of the underlying integer.</returns>
                public override string ToString() => Value.ToString(null, global::System.Globalization.CultureInfo.InvariantCulture);

                /// <summary>
                /// Formats the identifier using invariant numeric formatting semantics.
                /// </summary>
                /// <param name="format">A standard or custom numeric format string. Null or empty uses the default integer representation.</param>
                /// <param name="formatProvider">Ignored. Formatting always uses invariant culture.</param>
                /// <returns>The formatted identifier.</returns>
                public string ToString(string? format, global::System.IFormatProvider? formatProvider) =>
                    Value.ToString(format, global::System.Globalization.CultureInfo.InvariantCulture);

                /// <summary>
                /// Tries to format the identifier into the supplied character span without allocating a string.
                /// </summary>
                /// <param name="destination">The span that receives the formatted identifier.</param>
                /// <param name="charsWritten">When successful, receives the number of characters written.</param>
                /// <param name="format">A standard or custom numeric format. Empty uses the default integer representation.</param>
                /// <param name="provider">Ignored. Formatting always uses invariant culture.</param>
                /// <returns><see langword="true"/> if the destination was large enough; otherwise, <see langword="false"/>.</returns>
                public bool TryFormat(global::System.Span<char> destination, out int charsWritten, global::System.ReadOnlySpan<char> format = default, global::System.IFormatProvider? provider = null) =>
                    Value.TryFormat(destination, out charsWritten, format, global::System.Globalization.CultureInfo.InvariantCulture);

                /// <summary>
                /// Explicitly converts an underlying numeric value to the strongly typed identifier.
                /// </summary>
                /// <param name="value">The underlying numeric value.</param>
                /// <returns>A strongly typed identifier containing the exact numeric value.</returns>
                public static explicit operator {{typeName}}({{backingType}} value) => new(value);

                /// <summary>
                /// Explicitly converts the strongly typed identifier to its underlying numeric value.
                /// </summary>
                /// <param name="value">The strongly typed identifier.</param>
                /// <returns>The exact underlying numeric value.</returns>
                public static explicit operator {{backingType}}({{typeName}} value) => value.Value;

                /// <summary>
                /// Provides provider-neutral conversion expressions between this strongly typed identifier and its backing value.
                /// </summary>
                public static class StrongIdConversion
                {
                    /// <summary>
                    /// Gets the conversion expression from the strongly typed identifier to its backing value.
                    /// </summary>
                    public static global::System.Linq.Expressions.Expression<global::System.Func<{{typeName}}, {{backingType}}>> ToBackingValue { get; } = static value => value.Value;

                    /// <summary>
                    /// Gets the conversion expression from the backing value to the strongly typed identifier.
                    /// </summary>
                    public static global::System.Linq.Expressions.Expression<global::System.Func<{{backingType}}, {{typeName}}>> FromBackingValue { get; } = static value => new {{typeName}}(value);
                }

                /// <summary>
                /// Converts this strongly typed identifier to and from its scalar System.Text.Json representation.
                /// </summary>
                public sealed class StrongIdJsonConverter : global::System.Text.Json.Serialization.JsonConverter<{{typeName}}>
                {
                    /// <summary>
                    /// Initializes a new instance of the generated Strong ID JSON converter.
                    /// </summary>
                    public StrongIdJsonConverter()
                    {
                    }

                    /// <inheritdoc />
                    public override bool HandleNull => true;

                    /// <inheritdoc />
                    public override {{typeName}} Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
                    {
                        if (reader.TokenType != global::System.Text.Json.JsonTokenType.Number)
                        {
                            throw new global::System.Text.Json.JsonException("Expected a JSON number token for {{typeName}}.");
                        }

                        if (!reader.{{(backingKeyword == "int" ? "TryGetInt32" : "TryGetInt64")}}(out var value))
                        {
                            throw new global::System.Text.Json.JsonException("Invalid numeric value for {{typeName}}.");
                        }

                        return new {{typeName}}(value);
                    }

                    /// <inheritdoc />
                    public override void Write(global::System.Text.Json.Utf8JsonWriter writer, {{typeName}} value, global::System.Text.Json.JsonSerializerOptions options)
                    {
                        writer.WriteNumberValue(value.Value);
                    }
                }
            }

            """;

        Assert.Equal(expected.ReplaceLineEndings("\n"), generated.Source);
        Assert.DoesNotContain("\r", generated.Source, StringComparison.Ordinal);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
    }

    [Fact]
    public void NumericStrongIds_RoundTripBoundariesOverflowAndInvariantFormatting()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using System.Globalization;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<int>]
            public readonly partial record struct IntId;

            [StronglyTypedId<long>]
            public readonly partial record struct LongId;

            public static class NumericStrongIdProbe
            {
                public static bool Verify()
                {
                    var previousCulture = CultureInfo.CurrentCulture;
                    var previousUiCulture = CultureInfo.CurrentUICulture;

                    try
                    {
                        CultureInfo.CurrentCulture = new CultureInfo("fa-IR");
                        CultureInfo.CurrentUICulture = new CultureInfo("fa-IR");

                        if (!VerifyInt(int.MinValue) ||
                            !VerifyInt(-42) ||
                            !VerifyInt(0) ||
                            !VerifyInt(int.MaxValue) ||
                            !VerifyLong(long.MinValue) ||
                            !VerifyLong(-42L) ||
                            !VerifyLong(0L) ||
                            !VerifyLong(long.MaxValue))
                        {
                            return false;
                        }

                        var formattedInt = (IntId)1234567;
                        var formattedLong = (LongId)1234567890123L;
                        if (!string.Equals(formattedInt.ToString("N0", CultureInfo.CurrentCulture), "1,234,567", StringComparison.Ordinal) ||
                            !string.Equals(formattedLong.ToString("N0", CultureInfo.CurrentCulture), "1,234,567,890,123", StringComparison.Ordinal))
                        {
                            return false;
                        }

                        if (IntId.TryParse("1,234", CultureInfo.CurrentCulture, out _) ||
                            LongId.TryParse("1,234", CultureInfo.CurrentCulture, out _))
                        {
                            return false;
                        }

                        if (IntId.TryParse("2147483648", out var intOverflow) || !intOverflow.IsDefault ||
                            LongId.TryParse("9223372036854775808", out var longOverflow) || !longOverflow.IsDefault)
                        {
                            return false;
                        }

                        try
                        {
                            _ = IntId.Parse("2147483648");
                            return false;
                        }
                        catch (OverflowException)
                        {
                        }

                        try
                        {
                            _ = LongId.Parse("9223372036854775808");
                            return false;
                        }
                        catch (OverflowException)
                        {
                        }

                        return true;
                    }
                    finally
                    {
                        CultureInfo.CurrentCulture = previousCulture;
                        CultureInfo.CurrentUICulture = previousUiCulture;
                    }
                }

                private static bool VerifyInt(int value)
                {
                    var id = (IntId)value;
                    var expected = value.ToString(null, CultureInfo.InvariantCulture);
                    if ((int)id != value ||
                        id.Value != value ||
                        id.IsDefault != (value == 0) ||
                        !string.Equals(id.ToString(), expected, StringComparison.Ordinal) ||
                        IntId.Parse(expected, CultureInfo.CurrentCulture) != id ||
                        IntId.Parse(expected.AsSpan(), CultureInfo.CurrentCulture) != id ||
                        !IntId.TryParse(expected, CultureInfo.CurrentCulture, out var parsed) ||
                        parsed != id)
                    {
                        return false;
                    }

                    Span<char> buffer = stackalloc char[32];
                    if (!id.TryFormat(buffer, out var charsWritten, default, CultureInfo.CurrentCulture))
                    {
                        return false;
                    }

                    return string.Equals(new string(buffer[..charsWritten]), expected, StringComparison.Ordinal);
                }

                private static bool VerifyLong(long value)
                {
                    var id = (LongId)value;
                    var expected = value.ToString(null, CultureInfo.InvariantCulture);
                    if ((long)id != value ||
                        id.Value != value ||
                        id.IsDefault != (value == 0L) ||
                        !string.Equals(id.ToString(), expected, StringComparison.Ordinal) ||
                        LongId.Parse(expected, CultureInfo.CurrentCulture) != id ||
                        LongId.Parse(expected.AsSpan(), CultureInfo.CurrentCulture) != id ||
                        !LongId.TryParse(expected.AsSpan(), CultureInfo.CurrentCulture, out var parsed) ||
                        parsed != id)
                    {
                        return false;
                    }

                    Span<char> buffer = stackalloc char[32];
                    if (!id.TryFormat(buffer, out var charsWritten, default, CultureInfo.CurrentCulture))
                    {
                        return false;
                    }

                    return string.Equals(new string(buffer[..charsWritten]), expected, StringComparison.Ordinal);
                }
            }
            """);

        var result = RunGenerator(compilation);
        Assert.Empty(result.GeneratorDiagnostics);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));

        var assembly = EmitAndLoad(result.OutputCompilation);
        var probeType = Assert.IsAssignableFrom<Type>(assembly.GetType("NumericStrongIdProbe"));
        var verify = Assert.IsAssignableFrom<MethodInfo>(probeType.GetMethod("Verify", BindingFlags.Public | BindingFlags.Static));

        Assert.True(Assert.IsType<bool>(verify.Invoke(null, null)));
    }

    [Fact]
    public void NumericStrongIds_ExposeOnlyExplicitPrimitiveConversions()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<int>]
            public readonly partial record struct IntId;

            [StronglyTypedId<long>]
            public readonly partial record struct LongId;
            """);

        var result = RunGenerator(compilation);

        foreach (var (idMetadataName, primitiveMetadataName) in new[]
                 {
                     ("IntId", "System.Int32"),
                     ("LongId", "System.Int64")
                 })
        {
            var id = Assert.IsAssignableFrom<ITypeSymbol>(result.OutputCompilation.GetTypeByMetadataName(idMetadataName));
            var primitive = Assert.IsAssignableFrom<ITypeSymbol>(result.OutputCompilation.GetTypeByMetadataName(primitiveMetadataName));
            var toPrimitive = result.OutputCompilation.ClassifyConversion(id, primitive);
            var fromPrimitive = result.OutputCompilation.ClassifyConversion(primitive, id);

            Assert.False(toPrimitive.IsImplicit);
            Assert.False(fromPrimitive.IsImplicit);
            Assert.True(toPrimitive.IsExplicit);
            Assert.True(fromPrimitive.IsExplicit);
            Assert.DoesNotContain(
                id.GetMembers().OfType<IMethodSymbol>(),
                static member => member.MethodKind == MethodKind.Conversion && member.Name == "op_Implicit");
            Assert.Equal(
                2,
                id.GetMembers().OfType<IMethodSymbol>().Count(
                    static member => member.MethodKind == MethodKind.Conversion && member.Name == "op_Explicit"));
        }
    }

    [Fact]
    public void Generator_ReportsNonPartialStrongIdDeclaration()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly record struct OrderId;
            """);

        var result = RunGenerator(compilation);

        var diagnostic = Assert.Single(result.GeneratorDiagnostics);
        Assert.Equal("TCJ4000", diagnostic.Id);
        Assert.Equal(DiagnosticSeverity.Error, diagnostic.Severity);
        Assert.Contains("OrderId", diagnostic.GetMessage(), StringComparison.Ordinal);
        Assert.Empty(result.GeneratedSources);
        Assert.Null(result.GeneratorException);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static item => item.Severity == DiagnosticSeverity.Error));
    }

    [Theory]
    [InlineData("public partial record struct OrderId;")]
    [InlineData("public readonly partial struct OrderId { }")]
    [InlineData("public partial class OrderId { }")]
    [InlineData("file readonly partial record struct OrderId;")]
    public void Generator_ReportsUnsupportedStrongIdDeclarationShapes(string declaration)
    {
        var compilation = CreateCompilation(
            AttributeSource,
            $$"""
            using System;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            {{declaration}}
            """);

        var result = RunGenerator(compilation);

        var diagnostic = Assert.Single(result.GeneratorDiagnostics);
        Assert.Equal("TCJ4001", diagnostic.Id);
        Assert.Equal(DiagnosticSeverity.Error, diagnostic.Severity);
        Assert.Contains("OrderId", diagnostic.GetMessage(), StringComparison.Ordinal);
        Assert.Empty(result.GeneratedSources);
        Assert.Null(result.GeneratorException);
    }

    [Fact]
    public void Generator_ReportsNestedStrongIdAsUnsupportedShape()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            public static class Container
            {
                [StronglyTypedId<Guid>]
                public readonly partial record struct OrderId;
            }
            """);

        var result = RunGenerator(compilation);

        Assert.Equal("TCJ4001", Assert.Single(result.GeneratorDiagnostics).Id);
        Assert.Empty(result.GeneratedSources);
        Assert.Null(result.GeneratorException);
    }

    [Fact]
    public void Generator_ReportsUnsupportedStrongIdBackingType()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<decimal>]
            public readonly partial record struct MoneyId;
            """);

        var result = RunGenerator(compilation);

        var diagnostic = Assert.Single(result.GeneratorDiagnostics);
        Assert.Equal("TCJ4002", diagnostic.Id);
        Assert.Equal(DiagnosticSeverity.Error, diagnostic.Severity);
        Assert.Contains("decimal", diagnostic.GetMessage(), StringComparison.Ordinal);
        Assert.Empty(result.GeneratedSources);
        Assert.Null(result.GeneratorException);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static item => item.Severity == DiagnosticSeverity.Error));
    }

    [Fact]
    public void Generator_ReportsGenericStrongIdDeclaration()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId<T>;
            """);

        var result = RunGenerator(compilation);

        var diagnostic = Assert.Single(result.GeneratorDiagnostics);
        Assert.Equal("TCJ4003", diagnostic.Id);
        Assert.Equal(DiagnosticSeverity.Error, diagnostic.Severity);
        Assert.Contains("OrderId", diagnostic.GetMessage(), StringComparison.Ordinal);
        Assert.Empty(result.GeneratedSources);
        Assert.Null(result.GeneratorException);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static item => item.Severity == DiagnosticSeverity.Error));
    }

    [Fact]
    public void Generator_ReportsEveryConflictingUserDefinedGeneratedApiMember()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.Identifiers;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId
            {
                public OrderId(Guid value) { Value = value; }
                public Guid Value { get; }
                public static OrderId Parse(string value) => default;
                public static explicit operator OrderId(Guid value) => default;
                public static OrderId New(IGuidGenerator generator) => default;
                public static class StrongIdConversion { }
                public sealed class StrongIdJsonConverter { }
            }
            """);

        var result = RunGenerator(compilation);

        Assert.Equal(7, result.GeneratorDiagnostics.Count);
        Assert.All(result.GeneratorDiagnostics, static diagnostic =>
        {
            Assert.Equal("TCJ4004", diagnostic.Id);
            Assert.Equal(DiagnosticSeverity.Error, diagnostic.Severity);
            Assert.True(diagnostic.Location.IsInSource);
        });
        Assert.Contains(result.GeneratorDiagnostics, static diagnostic => diagnostic.GetMessage().Contains("Value", StringComparison.Ordinal));
        Assert.Contains(result.GeneratorDiagnostics, static diagnostic => diagnostic.GetMessage().Contains("Parse", StringComparison.Ordinal));
        Assert.Contains(result.GeneratorDiagnostics, static diagnostic => diagnostic.GetMessage().Contains("operator", StringComparison.Ordinal));
        Assert.Contains(result.GeneratorDiagnostics, static diagnostic => diagnostic.GetMessage().Contains("New", StringComparison.Ordinal));
        Assert.Contains(result.GeneratorDiagnostics, static diagnostic => diagnostic.GetMessage().Contains("StrongIdConversion", StringComparison.Ordinal));
        Assert.Contains(result.GeneratorDiagnostics, static diagnostic => diagnostic.GetMessage().Contains("StrongIdJsonConverter", StringComparison.Ordinal));
        var collisionLocations = result.GeneratorDiagnostics.Select(GetDiagnosticLocationText).ToArray();
        Assert.Contains("Value", collisionLocations);
        Assert.Contains("Parse", collisionLocations);
        Assert.Contains("StrongIdJsonConverter", collisionLocations);
        Assert.Empty(result.GeneratedSources);
        Assert.Null(result.GeneratorException);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
    }

    [Fact]
    public void Generator_ReportsNonMethodMemberNamedLikeGeneratedMethod()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId
            {
                public static int Parse => 0;
            }
            """);

        var result = RunGenerator(compilation);

        var diagnostic = Assert.Single(result.GeneratorDiagnostics);
        Assert.Equal("TCJ4004", diagnostic.Id);
        Assert.Equal(DiagnosticSeverity.Error, diagnostic.Severity);
        Assert.True(diagnostic.Location.IsInSource);
        Assert.Contains("Parse", diagnostic.GetMessage(), StringComparison.Ordinal);
        Assert.Empty(result.GeneratedSources);
        Assert.Null(result.GeneratorException);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static item => item.Severity == DiagnosticSeverity.Error));
    }

    [Fact]
    public void Generator_ReportsRefOutSignatureCollision()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId
            {
                public static bool TryParse(string? value, ref OrderId result) => false;
            }
            """);

        var result = RunGenerator(compilation);

        var diagnostic = Assert.Single(result.GeneratorDiagnostics);
        Assert.Equal("TCJ4004", diagnostic.Id);
        Assert.Contains("TryParse", diagnostic.GetMessage(), StringComparison.Ordinal);
        Assert.Empty(result.GeneratedSources);
        Assert.Null(result.GeneratorException);
        Assert.Empty(compilation.GetDiagnostics().Where(static item => item.Severity == DiagnosticSeverity.Error));
    }

    [Fact]
    public void Generator_AllowsNonConflictingUserDefinedOverloads()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId
            {
                public static OrderId Parse(int value) => default;
                public static OrderId New() => default;
            }
            """);

        var result = RunGenerator(compilation);

        Assert.Empty(result.GeneratorDiagnostics);
        Assert.Single(result.GeneratedSources);
        Assert.Null(result.GeneratorException);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
    }

    [Fact]
    public void Generator_ReportsAmbiguousStrongIdAndValueObjectAttributesAtBothAttributes()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            [ValueObject<Guid>]
            public readonly partial record struct OrderId;
            """);

        var result = RunGenerator(compilation);

        Assert.Equal(2, result.GeneratorDiagnostics.Count);
        Assert.All(result.GeneratorDiagnostics, static diagnostic =>
        {
            Assert.Equal("TCJ4005", diagnostic.Id);
            Assert.Equal(DiagnosticSeverity.Error, diagnostic.Severity);
            Assert.True(diagnostic.Location.IsInSource);
        });
        Assert.Contains(result.GeneratorDiagnostics, static diagnostic => diagnostic.GetMessage().Contains("StronglyTypedIdAttribute", StringComparison.Ordinal));
        Assert.Contains(result.GeneratorDiagnostics, static diagnostic => diagnostic.GetMessage().Contains("ValueObjectAttribute", StringComparison.Ordinal));
        var attributeLocations = result.GeneratorDiagnostics.Select(GetDiagnosticLocationText).ToArray();
        Assert.Contains(attributeLocations, static text => text.Contains("StronglyTypedId<Guid>", StringComparison.Ordinal));
        Assert.Contains(attributeLocations, static text => text.Contains("ValueObject<Guid>", StringComparison.Ordinal));
        Assert.Empty(result.GeneratedSources);
        Assert.Null(result.GeneratorException);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
    }

    [Fact]
    public void Generator_ReportsDuplicateStrongIdAttributesAtEachAttribute()
    {
        var compilation = CreateCompilation(
            RepeatableStrongIdAttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;
            """);

        var result = RunGenerator(compilation);

        Assert.Equal(2, result.GeneratorDiagnostics.Count);
        Assert.All(result.GeneratorDiagnostics, static diagnostic => Assert.Equal("TCJ4005", diagnostic.Id));
        Assert.Empty(result.GeneratedSources);
        Assert.Null(result.GeneratorException);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
    }

    [Fact]
    public void Generator_DeduplicatesDuplicateAttributeDiagnosticsAcrossPartialDeclarations()
    {
        var compilation = CreateCompilation(
            RepeatableStrongIdAttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;
            """,
            """
            using System;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;
            """);

        var result = RunGenerator(compilation);

        Assert.Equal(2, result.GeneratorDiagnostics.Count);
        Assert.All(result.GeneratorDiagnostics, static diagnostic => Assert.Equal("TCJ4005", diagnostic.Id));
        Assert.Empty(result.GeneratedSources);
        Assert.Null(result.GeneratorException);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
    }

    [Fact]
    public void InvalidStrongId_DoesNotBlockValidUnrelatedStrongIdOrChangeItsHintName()
    {
        var validOnly = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            namespace Sales;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;
            """);
        var withInvalid = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            namespace Sales;

            [StronglyTypedId<Guid>]
            public readonly record struct BrokenId;

            [StronglyTypedId<Guid>]
            public readonly partial record struct OrderId;
            """);

        var validResult = RunGenerator(validOnly);
        var mixedResult = RunGenerator(withInvalid);

        Assert.Empty(validResult.GeneratorDiagnostics);
        Assert.Equal("TCJ4000", Assert.Single(mixedResult.GeneratorDiagnostics).Id);
        var validSource = Assert.Single(validResult.GeneratedSources);
        var mixedSource = Assert.Single(mixedResult.GeneratedSources);
        Assert.Equal(validSource.HintName, mixedSource.HintName);
        Assert.Equal(validSource.Source, mixedSource.Source);
        Assert.Equal("TCJ.StronglyTypedId.Sales.OrderId.g.cs", mixedSource.HintName);
        Assert.Null(mixedResult.GeneratorException);
    }

    [Fact]
    public void Generator_DiagnosticOrdering_IsDeterministicAcrossInvalidTypes()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<decimal>]
            public readonly partial record struct ZuluId;

            [StronglyTypedId<Guid>]
            public readonly record struct AlphaId;
            """);

        var first = RunGenerator(compilation);
        var second = RunGenerator(compilation);

        Assert.Equal(
            first.GeneratorDiagnostics.Select(static diagnostic => (diagnostic.Id, diagnostic.GetMessage())),
            second.GeneratorDiagnostics.Select(static diagnostic => (diagnostic.Id, diagnostic.GetMessage())));
        Assert.Equal(new[] { "TCJ4000", "TCJ4002" }, first.GeneratorDiagnostics.Select(static diagnostic => diagnostic.Id));
        Assert.Contains("AlphaId", first.GeneratorDiagnostics[0].GetMessage(), StringComparison.Ordinal);
        Assert.Contains("ZuluId", first.GeneratorDiagnostics[1].GetMessage(), StringComparison.Ordinal);
        Assert.Null(first.GeneratorException);
        Assert.Null(second.GeneratorException);
    }

    [Fact]
    public void StrongIds_JsonRoundTripAsBackingScalars()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using System.Text.Json;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct GuidId;

            [StronglyTypedId<int>]
            public readonly partial record struct IntId;

            [StronglyTypedId<long>]
            public readonly partial record struct LongId;

            public static class StrongIdJsonProbe
            {
                public static bool VerifyRoundTrips()
                {
                    var guid = Guid.Parse("7a29be31-268d-4f2b-babc-fce0ce1cb46c");
                    var guidId = new GuidId(guid);
                    var intId = new IntId(-42);
                    var longId = new LongId(long.MaxValue);

                    string guidJson = JsonSerializer.Serialize(guidId);
                    string intJson = JsonSerializer.Serialize(intId);
                    string longJson = JsonSerializer.Serialize(longId);

                    return string.Equals(guidJson, "\"7a29be31-268d-4f2b-babc-fce0ce1cb46c\"", StringComparison.Ordinal) &&
                           string.Equals(intJson, "-42", StringComparison.Ordinal) &&
                           string.Equals(longJson, "9223372036854775807", StringComparison.Ordinal) &&
                           JsonSerializer.Deserialize<GuidId>(guidJson) == guidId &&
                           JsonSerializer.Deserialize<IntId>(intJson) == intId &&
                           JsonSerializer.Deserialize<LongId>(longJson) == longId;
                }
            }
            """);

        var result = RunGenerator(compilation);
        Assert.Empty(result.GeneratorDiagnostics);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));

        var assembly = EmitAndLoad(result.OutputCompilation);
        var probeType = Assert.IsAssignableFrom<Type>(assembly.GetType("StrongIdJsonProbe"));
        var verify = Assert.IsAssignableFrom<MethodInfo>(probeType.GetMethod("VerifyRoundTrips", BindingFlags.Public | BindingFlags.Static));

        Assert.True(Assert.IsType<bool>(verify.Invoke(null, null)));
    }

    [Fact]
    public void StrongIds_JsonRejectInvalidTokensMalformedValuesAndNullWithoutEchoingRawValues()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using System.Text.Json;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct GuidId;

            [StronglyTypedId<int>]
            public readonly partial record struct IntId;

            [StronglyTypedId<long>]
            public readonly partial record struct LongId;

            public static class StrongIdJsonInvalidProbe
            {
                public static bool VerifyInvalidInputs()
                {
                    return ThrowsJson<GuidId>("123") &&
                           ThrowsJsonWithoutEcho<GuidId>("\"not-a-guid-secret\"", "not-a-guid-secret") &&
                           ThrowsJson<GuidId>("null") &&
                           ThrowsJson<IntId>("\"42\"") &&
                           ThrowsJson<IntId>("1.5") &&
                           ThrowsJsonWithoutEcho<IntId>("2147483648", "2147483648") &&
                           ThrowsJson<IntId>("null") &&
                           ThrowsJson<LongId>("\"42\"") &&
                           ThrowsJsonWithoutEcho<LongId>("9223372036854775808", "9223372036854775808") &&
                           ThrowsJson<LongId>("null");
                }

                private static bool ThrowsJson<T>(string json)
                {
                    try
                    {
                        _ = JsonSerializer.Deserialize<T>(json);
                        return false;
                    }
                    catch (JsonException)
                    {
                        return true;
                    }
                }

                private static bool ThrowsJsonWithoutEcho<T>(string json, string rawValue)
                {
                    try
                    {
                        _ = JsonSerializer.Deserialize<T>(json);
                        return false;
                    }
                    catch (JsonException exception)
                    {
                        return !exception.Message.Contains(rawValue, StringComparison.Ordinal);
                    }
                }
            }
            """);

        var result = RunGenerator(compilation);
        Assert.Empty(result.GeneratorDiagnostics);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));

        var assembly = EmitAndLoad(result.OutputCompilation);
        var probeType = Assert.IsAssignableFrom<Type>(assembly.GetType("StrongIdJsonInvalidProbe"));
        var verify = Assert.IsAssignableFrom<MethodInfo>(probeType.GetMethod("VerifyInvalidInputs", BindingFlags.Public | BindingFlags.Static));

        Assert.True(Assert.IsType<bool>(verify.Invoke(null, null)));
    }

    [Fact]
    public void StrongIdConversionExpressions_AreGeneratedWithoutEfOrRuntimeTypeActivation()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct GuidId;

            [StronglyTypedId<int>]
            public readonly partial record struct IntId;

            [StronglyTypedId<long>]
            public readonly partial record struct LongId;
            """);

        var result = RunGenerator(compilation);

        Assert.Equal(3, result.GeneratedSources.Count);
        foreach (var generated in result.GeneratedSources)
        {
            Assert.Contains("public static class StrongIdConversion", generated.Source, StringComparison.Ordinal);
            Assert.Contains("global::System.Linq.Expressions.Expression<global::System.Func<", generated.Source, StringComparison.Ordinal);
            Assert.Contains("ToBackingValue { get; } = static value => value.Value;", generated.Source, StringComparison.Ordinal);
            Assert.Contains("FromBackingValue { get; } = static value => new ", generated.Source, StringComparison.Ordinal);
            Assert.DoesNotContain("Microsoft.EntityFrameworkCore", generated.Source, StringComparison.Ordinal);
            Assert.DoesNotContain("MakeGenericType", generated.Source, StringComparison.Ordinal);
            Assert.DoesNotContain("System.Reflection", generated.Source, StringComparison.Ordinal);
            Assert.DoesNotContain("Activator", generated.Source, StringComparison.Ordinal);
            Assert.DoesNotContain("Assembly.", generated.Source, StringComparison.Ordinal);
        }
    }

    [Fact]
    public void StrongIdJsonConverters_AreDedicatedAndDoNotUseReflectionFactoriesOrRuntimeCodeGeneration()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.StrongTypes;

            [StronglyTypedId<Guid>]
            public readonly partial record struct GuidId;

            [StronglyTypedId<int>]
            public readonly partial record struct IntId;

            [StronglyTypedId<long>]
            public readonly partial record struct LongId;
            """);

        var result = RunGenerator(compilation);

        Assert.Equal(3, result.GeneratedSources.Count);
        foreach (var generated in result.GeneratedSources)
        {
            Assert.Contains("public sealed class StrongIdJsonConverter : global::System.Text.Json.Serialization.JsonConverter<", generated.Source, StringComparison.Ordinal);
            Assert.Contains("Serialization.JsonConverter(typeof(", generated.Source, StringComparison.Ordinal);
            Assert.DoesNotContain("JsonConverterFactory", generated.Source, StringComparison.Ordinal);
            Assert.DoesNotContain("MakeGenericType", generated.Source, StringComparison.Ordinal);
            Assert.DoesNotContain("System.Reflection", generated.Source, StringComparison.Ordinal);
            Assert.DoesNotContain("GetType(", generated.Source, StringComparison.Ordinal);
            Assert.DoesNotContain("Activator", generated.Source, StringComparison.Ordinal);
        }
    }

    [Fact]
    public void ValueObject_GeneratedSource_UsesValidatedPrivateConstruction()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using TCJ.Core.Results;
            using TCJ.Core.StrongTypes;

            namespace Sales.Customers;

            [ValueObject<string>]
            public readonly partial record struct EmailAddress
            {
                private static Result Validate(string value) => Result.Success();
            }
            """);

        var result = RunGenerator(compilation);

        Assert.Empty(result.GeneratorDiagnostics);
        var generated = Assert.Single(result.GeneratedSources);
        Assert.Equal("TCJ.ValueObject.Sales.Customers.EmailAddress.g.cs", generated.HintName);
        Assert.Contains("private EmailAddress(global::System.String value)", generated.Source, StringComparison.Ordinal);
        Assert.Contains("public global::System.String Value { get; }", generated.Source, StringComparison.Ordinal);
        Assert.Contains("public bool IsDefault", generated.Source, StringComparison.Ordinal);
        Assert.Contains("public static global::TCJ.Core.Results.Result<EmailAddress> Create(global::System.String value)", generated.Source, StringComparison.Ordinal);
        Assert.Contains("var validation = Validate(value)", generated.Source, StringComparison.Ordinal);
        Assert.Contains("Result.Failure<EmailAddress>(validation.Errors)", generated.Source, StringComparison.Ordinal);
        Assert.DoesNotContain("public EmailAddress(global::System.String value)", generated.Source, StringComparison.Ordinal);
        Assert.DoesNotContain("System.Reflection", generated.Source, StringComparison.Ordinal);
        Assert.DoesNotContain("Activator", generated.Source, StringComparison.Ordinal);
    }

    [Fact]
    public void ValueObject_Create_PreservesValidationErrorsAndUsesRecordEqualityAndDefaultSemantics()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using TCJ.Core.Results;
            using TCJ.Core.StrongTypes;

            [ValueObject<string>]
            public readonly partial record struct EmailAddress
            {
                public static readonly ResultError RequiredError = new("email.required", "Email is required.");
                public static readonly ResultError FormatError = new("email.format", "Email format is invalid.");

                private static Result Validate(string value)
                {
                    return string.IsNullOrWhiteSpace(value)
                        ? Result.Failure(new[] { RequiredError, FormatError })
                        : Result.Success();
                }
            }
            """);

        var result = RunGenerator(compilation);
        Assert.Empty(result.GeneratorDiagnostics);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));

        var assembly = EmitAndLoad(result.OutputCompilation);
        var type = Assert.IsAssignableFrom<Type>(assembly.GetType("EmailAddress"));
        var create = Assert.IsAssignableFrom<MethodInfo>(type.GetMethod("Create", BindingFlags.Public | BindingFlags.Static));
        var valueProperty = Assert.IsAssignableFrom<PropertyInfo>(type.GetProperty("Value"));
        var isDefaultProperty = Assert.IsAssignableFrom<PropertyInfo>(type.GetProperty("IsDefault"));

        var successResult = create.Invoke(null, new object?[] { "user@example.com" });
        Assert.NotNull(successResult);
        Assert.True(Assert.IsType<bool>(successResult!.GetType().GetProperty("IsSuccess")!.GetValue(successResult)));
        var first = successResult.GetType().GetProperty("Value")!.GetValue(successResult);
        Assert.NotNull(first);

        var secondResult = create.Invoke(null, new object?[] { "user@example.com" });
        Assert.NotNull(secondResult);
        var second = secondResult!.GetType().GetProperty("Value")!.GetValue(secondResult);
        Assert.NotNull(second);
        Assert.Equal(first, second);
        Assert.Equal(first.GetHashCode(), second.GetHashCode());
        Assert.Equal("user@example.com", valueProperty.GetValue(first));
        Assert.False(Assert.IsType<bool>(isDefaultProperty.GetValue(first)));

        var failureResult = create.Invoke(null, new object?[] { "" });
        Assert.NotNull(failureResult);
        Assert.True(Assert.IsType<bool>(failureResult!.GetType().GetProperty("IsFailure")!.GetValue(failureResult)));
        var errors = Assert.IsAssignableFrom<System.Collections.IEnumerable>(failureResult.GetType().GetProperty("Errors")!.GetValue(failureResult))
            .Cast<object>()
            .ToArray();
        Assert.Equal(2, errors.Length);
        Assert.Same(type.GetField("RequiredError", BindingFlags.Public | BindingFlags.Static)!.GetValue(null), errors[0]);
        Assert.Same(type.GetField("FormatError", BindingFlags.Public | BindingFlags.Static)!.GetValue(null), errors[1]);

        var defaultValue = Activator.CreateInstance(type);
        Assert.NotNull(defaultValue);
        Assert.Null(valueProperty.GetValue(defaultValue));
        Assert.True(Assert.IsType<bool>(isDefaultProperty.GetValue(defaultValue)));

        Assert.Null(type.GetConstructor(new[] { typeof(string) }));
        Assert.NotNull(type.GetConstructor(
            BindingFlags.NonPublic | BindingFlags.Instance,
            binder: null,
            new[] { typeof(string) },
            modifiers: null));
    }

    [Theory]
    [InlineData("string", "global::System.String", "StringValue")]
    [InlineData("System.Guid", "global::System.Guid", "GuidValue")]
    [InlineData("int", "global::System.Int32", "IntValue")]
    [InlineData("long", "global::System.Int64", "LongValue")]
    [InlineData("decimal", "global::System.Decimal", "DecimalValue")]
    public void ValueObject_SupportsEveryV1BackingType(string backingType, string expectedBackingType, string typeName)
    {
        var compilation = CreateCompilation(
            AttributeSource,
            $$"""
            using TCJ.Core.Results;
            using TCJ.Core.StrongTypes;

            [ValueObject<{{backingType}}>]
            public readonly partial record struct {{typeName}}
            {
                private static Result Validate({{backingType}} value) => Result.Success();
            }
            """);

        var result = RunGenerator(compilation);

        Assert.Empty(result.GeneratorDiagnostics);
        Assert.Empty(result.OutputCompilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
        var generated = Assert.Single(result.GeneratedSources);
        Assert.Equal($"TCJ.ValueObject.{typeName}.g.cs", generated.HintName);

        var generatedType = Assert.IsAssignableFrom<INamedTypeSymbol>(result.OutputCompilation.GetTypeByMetadataName(typeName));
        var value = Assert.IsAssignableFrom<IPropertySymbol>(generatedType.GetMembers("Value").Single());
        Assert.Equal(expectedBackingType, value.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        var create = Assert.IsAssignableFrom<IMethodSymbol>(generatedType.GetMembers("Create").Single());
        var returnType = Assert.IsAssignableFrom<INamedTypeSymbol>(create.ReturnType);
        Assert.Equal("Result", returnType.Name);
        Assert.Equal("TCJ.Core.Results", returnType.ContainingNamespace.ToDisplayString());
        Assert.True(SymbolEqualityComparer.Default.Equals(generatedType, Assert.Single(returnType.TypeArguments)));
    }

    [Theory]
    [InlineData("")]
    [InlineData("private static Result Validate(int value) => Result.Success();")]
    [InlineData("private Result Validate(string value) => Result.Success();")]
    [InlineData("private static Result<string> Validate(string value) => Result.Success(value);")]
    [InlineData("private static Result Validate(ref string value) => Result.Success();")]
    public void ValueObject_RequiresExactApplicationValidationSignature(string validateMember)
    {
        var compilation = CreateCompilation(
            AttributeSource,
            $$"""
            using TCJ.Core.Results;
            using TCJ.Core.StrongTypes;

            [ValueObject<string>]
            public readonly partial record struct EmailAddress
            {
                {{validateMember}}
            }
            """);

        var result = RunGenerator(compilation);

        var diagnostic = Assert.Single(result.GeneratorDiagnostics);
        Assert.Equal("TCJ4006", diagnostic.Id);
        Assert.Contains("Validate(string value)", diagnostic.GetMessage(), StringComparison.Ordinal);
        Assert.Empty(result.GeneratedSources);
        Assert.Null(result.GeneratorException);
    }

    [Theory]
    [InlineData("[ValueObject<string>] public readonly record struct EmailAddress { private static Result Validate(string value) => Result.Success(); }")]
    [InlineData("[ValueObject<string>] public partial record struct EmailAddress { private static Result Validate(string value) => Result.Success(); }")]
    [InlineData("[ValueObject<string>] public readonly partial record class EmailAddress { private static Result Validate(string value) => Result.Success(); }")]
    [InlineData("[ValueObject<string>] public readonly partial record struct EmailAddress<T> { private static Result Validate(string value) => Result.Success(); }")]
    public void ValueObject_RejectsUnsupportedDeclarationShapes(string declaration)
    {
        var compilation = CreateCompilation(
            AttributeSource,
            $$"""
            using TCJ.Core.Results;
            using TCJ.Core.StrongTypes;

            {{declaration}}
            """);

        var result = RunGenerator(compilation);

        Assert.NotEmpty(result.GeneratorDiagnostics);
        Assert.All(result.GeneratorDiagnostics, static diagnostic => Assert.Equal("TCJ4006", diagnostic.Id));
        Assert.Empty(result.GeneratedSources);
        Assert.Null(result.GeneratorException);
    }

    [Fact]
    public void ValueObject_RejectsUnsupportedBackingType()
    {
        var compilation = CreateCompilation(
            AttributeSource,
            """
            using System;
            using TCJ.Core.Results;
            using TCJ.Core.StrongTypes;

            [ValueObject<DateTime>]
            public readonly partial record struct LocalDate
            {
                private static Result Validate(DateTime value) => Result.Success();
            }
            """);

        var result = RunGenerator(compilation);

        var diagnostic = Assert.Single(result.GeneratorDiagnostics);
        Assert.Equal("TCJ4006", diagnostic.Id);
        Assert.Contains("unsupported", diagnostic.GetMessage(), StringComparison.OrdinalIgnoreCase);
        Assert.Empty(result.GeneratedSources);
        Assert.Null(result.GeneratorException);
    }

    [Theory]
    [InlineData("public string Value { get; }")]
    [InlineData("public bool IsDefault => false;")]
    [InlineData("public static EmailAddress Create(int value) => default;")]
    [InlineData("public EmailAddress() { }")]
    [InlineData("public EmailAddress(string value) { }")]
    public void ValueObject_RejectsMembersThatBypassOrCollideWithGeneratedApi(string conflictingMember)
    {
        var compilation = CreateCompilation(
            AttributeSource,
            $$"""
            using TCJ.Core.Results;
            using TCJ.Core.StrongTypes;

            [ValueObject<string>]
            public readonly partial record struct EmailAddress
            {
                private static Result Validate(string value) => Result.Success();

                {{conflictingMember}}
            }
            """);

        var result = RunGenerator(compilation);

        var diagnostic = Assert.Single(result.GeneratorDiagnostics);
        Assert.Equal("TCJ4007", diagnostic.Id);
        Assert.Empty(result.GeneratedSources);
        Assert.Null(result.GeneratorException);
    }

    private static string GetDiagnosticLocationText(Diagnostic diagnostic)
    {
        Assert.True(diagnostic.Location.IsInSource);
        var sourceTree = Assert.IsAssignableFrom<SyntaxTree>(diagnostic.Location.SourceTree);
        return sourceTree.GetText().ToString(diagnostic.Location.SourceSpan);
    }

    private static GeneratorResult RunGenerator(CSharpCompilation compilation)
    {
        GeneratorDriver driver = CSharpGeneratorDriver.Create(new StrongTypeGenerator());

        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation,
            out var outputCompilation,
            out var diagnostics);

        var runResult = driver.GetRunResult();
        var generatedSources = runResult.Results
            .Where(static result => !result.GeneratedSources.IsDefault)
            .SelectMany(static result => result.GeneratedSources)
            .Select(static source => new GeneratedSource(source.HintName, source.SourceText.ToString()))
            .OrderBy(static source => source.HintName, StringComparer.Ordinal)
            .ToArray();

        var generatorException = Assert.Single(runResult.Results).Exception;

        return new GeneratorResult(
            diagnostics,
            generatedSources,
            (CSharpCompilation)outputCompilation,
            generatorException);
    }

    private static CSharpCompilation CreateCompilation(params string[] sources)
    {
        var parseOptions = new CSharpParseOptions(LanguageVersion.Latest);
        var syntaxTrees = sources
            .Append(GuidGeneratorContractSource)
            .Append(ResultContractSource)
            .Select(source => CSharpSyntaxTree.ParseText(source, parseOptions))
            .ToArray();

        return CSharpCompilation.Create(
            "Test_" + Guid.NewGuid().ToString("N"),
            syntaxTrees,
            TrustedPlatformReferences,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    private static Assembly EmitAndLoad(CSharpCompilation compilation)
    {
        using var stream = new MemoryStream();
        var emitResult = compilation.Emit(stream);
        Assert.True(
            emitResult.Success,
            string.Join(Environment.NewLine, emitResult.Diagnostics.Select(static diagnostic => diagnostic.ToString())));

        return Assembly.Load(stream.ToArray());
    }

    private static readonly MetadataReference[] TrustedPlatformReferences =
        ((string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES"))!
        .Split(Path.PathSeparator)
        .Select(static path => MetadataReference.CreateFromFile(path))
        .ToArray();

    private sealed record GeneratedSource(string HintName, string Source);

    private sealed record GeneratorResult(
        IReadOnlyList<Diagnostic> GeneratorDiagnostics,
        IReadOnlyList<GeneratedSource> GeneratedSources,
        CSharpCompilation OutputCompilation,
        Exception? GeneratorException);

    private const string AttributeSource =
        """
        namespace TCJ.Core.StrongTypes;

        [System.AttributeUsage(System.AttributeTargets.Struct | System.AttributeTargets.Class)]
        public sealed class StronglyTypedIdAttribute<T> : System.Attribute
        {
        }

        [System.AttributeUsage(System.AttributeTargets.Struct | System.AttributeTargets.Class)]
        public sealed class ValueObjectAttribute<T> : System.Attribute
        {
        }
        """;

    private const string RepeatableStrongIdAttributeSource =
        """
        namespace TCJ.Core.StrongTypes;

        [System.AttributeUsage(System.AttributeTargets.Struct | System.AttributeTargets.Class, AllowMultiple = true)]
        public sealed class StronglyTypedIdAttribute<T> : System.Attribute
        {
        }

        [System.AttributeUsage(System.AttributeTargets.Struct | System.AttributeTargets.Class)]
        public sealed class ValueObjectAttribute<T> : System.Attribute
        {
        }
        """;


    private const string ResultContractSource =
        """
        #nullable enable

        namespace TCJ.Core.Results;

        public sealed class ResultError
        {
            public ResultError(string code, string message)
            {
                Code = code;
                Message = message;
            }

            public string Code { get; }

            public string Message { get; }
        }

        public class Result
        {
            private readonly System.Collections.Generic.IReadOnlyList<ResultError> _errors;

            protected Result(bool isSuccess, System.Collections.Generic.IEnumerable<ResultError> errors)
            {
                IsSuccess = isSuccess;
                _errors = new System.Collections.Generic.List<ResultError>(errors).AsReadOnly();
            }

            public bool IsSuccess { get; }

            public bool IsFailure => !IsSuccess;

            public System.Collections.Generic.IReadOnlyList<ResultError> Errors => _errors;

            public static Result Success() => new(true, System.Array.Empty<ResultError>());

            public static Result Failure(ResultError error) => new(false, new[] { error });

            public static Result Failure(System.Collections.Generic.IEnumerable<ResultError> errors) => new(false, errors);

            public static Result<T> Success<T>(T value) => new(value);

            public static Result<T> Failure<T>(System.Collections.Generic.IEnumerable<ResultError> errors) => new(errors);
        }

        public sealed class Result<T> : Result
        {
            private readonly T? _value;

            internal Result(T value) : base(true, System.Array.Empty<ResultError>())
            {
                _value = value;
            }

            internal Result(System.Collections.Generic.IEnumerable<ResultError> errors) : base(false, errors)
            {
            }

            public T Value => IsSuccess
                ? _value!
                : throw new System.InvalidOperationException("A failed result does not contain a value.");
        }
        """;

    private const string GuidGeneratorContractSource =
        """
        namespace TCJ.Core.Identifiers;

        public interface IGuidGenerator
        {
            System.Guid Create();

            System.Guid CreateVersion7();
        }
        """;
}
