<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\TestProject.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\TCJ.Generators\TCJ.Generators.csproj" />
  </ItemGroup>
</Project>
