<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TCJ.Core\TCJ.Core.csproj" />
    <ProjectReference Include="..\..\src\TCJ.Generators\TCJ.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" GlobalPropertiesToRemove="TreatWarningsAsErrors;WarningsNotAsErrors" />
  </ItemGroup>
</Project>
