<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <TCJPackageVersion Condition="'$(TCJPackageVersion)' == ''">0.1.0-preview.1</TCJPackageVersion>
    <RestoreSources>https://api.nuget.org/v3/index.json</RestoreSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TCJ.Core" Version="$(TCJPackageVersion)" />
    <PackageReference Include="TCJ.DependencyInjection" Version="$(TCJPackageVersion)" />
    <PackageReference Include="TCJ.EntityFrameworkCore" Version="$(TCJPackageVersion)" />
    <PackageReference Include="TCJ.EntityFrameworkCore.SqlServer" Version="$(TCJPackageVersion)" />
    <PackageReference Include="TCJ.AspNetCore" Version="$(TCJPackageVersion)" />
  </ItemGroup>
</Project>
