<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><IsAotCompatible>false</IsAotCompatible></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TCJ.Messaging" Version="$(TCJCompatibilityVersion)" />
    <PackageReference Include="TCJ.Messaging.AzureServiceBus" Version="$(TCJCompatibilityVersion)" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
  </ItemGroup>
</Project>
