// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TCJ.EntityFrameworkCore.SqlServer.IntegrationTests.Infrastructure;

#nullable disable

namespace TCJ.EntityFrameworkCore.SqlServer.IntegrationTests.Migrations;

[DbContext(typeof(SqlServerTestDbContext))]
[Migration("202608080001_InitialSqlServerIntegration")]
internal sealed partial class InitialSqlServerIntegrationMigration
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        SqlServerIntegrationMigrationModel.Build(modelBuilder);
    }
}
