// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using TCJ.EntityFrameworkCore.SqlServer.IntegrationTests.Infrastructure;

#nullable disable

namespace TCJ.EntityFrameworkCore.SqlServer.IntegrationTests.Migrations;

[DbContext(typeof(SqlServerTestDbContext))]
internal sealed class SqlServerTestDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        SqlServerIntegrationMigrationModel.Build(modelBuilder);
    }
}
