<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TCJ.Core" Version="$(TCJCompatibilityVersion)" />
    <PackageReference Include="TCJ.DependencyInjection" Version="$(TCJCompatibilityVersion)" />
    <PackageReference Include="TCJ.EntityFrameworkCore" Version="$(TCJCompatibilityVersion)" />
    <PackageReference Include="TCJ.EntityFrameworkCore.SqlServer" Version="$(TCJCompatibilityVersion)" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
  </ItemGroup>
</Project>
