<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\TCJ.Messaging\TCJ.Messaging.csproj" />
    <ProjectReference Include="..\..\src\TCJ.Messaging.AzureServiceBus\TCJ.Messaging.AzureServiceBus.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
</Project>
